"""Shared inference core for the Group 20 stunting screening tool.

Both ``app.py`` and ``self_test.py`` import this module, so the code path the
panel sees demonstrated is provably the same code path the reproduction check
in Section 3.13.4 validates.

Every transformation below is traced to its origin:

* median/mode imputation and standardisation -- notebook cell 14 (Task C),
  parameters re-derived and exported by the EP-5 cell into ``manifest.json``;
* one-hot encoding -- notebook cell 17 (Task D), restricted to the 31 features
  retained by the Stage 1 filter of Section 3.3.3;
* tier assignment -- Equations 3.15 to 3.17, Section 3.11.2.

No parameter is re-estimated from the records supplied to the tool, so a child
scored in isolation receives exactly the treatment it would have received
inside the test partition (Section 3.13.2).
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List, Sequence, Tuple

import numpy as np
import pandas as pd

# --------------------------------------------------------------------------
# Paths
# --------------------------------------------------------------------------

ROOT = Path(__file__).resolve().parent
ARTEFACTS = ROOT / "artefacts"
MANIFEST_PATH = ARTEFACTS / "manifest.json"
CODEBOOK_PATH = ARTEFACTS / "enns_codebook.csv"
THRESHOLDS_PATH = ARTEFACTS / "section_3_11_thresholds.json"
SURFACE_PATH = ARTEFACTS / "section_3_11_threshold_surface.csv"

# --------------------------------------------------------------------------
# Hard-coded expectations (Section 3.13.2)
#
# The application holds its own copy of the preprocessing parameters and
# compares them against the manifest before scoring anything. Where the two
# disagree the application refuses to score, because a tool preprocessing
# differently from the notebook returns values that look correct and are not
# the values reported in Chapter 4.
#
# Source of every number below: manifest.json exported 2026-09-13 07:41 from
# model_outputs/tool_bundle/, cross-checked against section_3_11_thresholds.json.
# --------------------------------------------------------------------------

EXPECTED_MODEL_NAME = "Exp4_ADASYN_XGB"
EXPECTED_SEVERE_INDEX = 2
EXPECTED_TAU_H = 0.09889556467533112
EXPECTED_TAU_M = 0.049

EXPECTED_IMPUTE: Dict[str, float] = {
    "weight": 11.69999980926514,
    "age": 2.822724104,
    "bedroom": 1.0,
    "fwealthq": 1.0,
    "roof": 6.0,
    "wall": 6.0,
    "floor": 8.0,
    "dweltype": 1.0,
    "tenurhws": 1.0,
    "tenurlot": 1.0,
    "electrct": 2.0,
    "wdrinkng": 91.0,
    "drinksafe": 0.0,
    "makesafe": 0.0,
    "toilet": 1.0,
    "fuelmain": 6.0,
    "collect": 0.0,
    "burn": 0.0,
    "dump": 0.0,
    "composting": 0.0,
    "segregate": 1.0,
}

EXPECTED_SCALER: Dict[str, Tuple[float, float]] = {
    "weight": (11.633574383551077, 3.4945029302608726),
    "age": (2.7028876781178597, 1.436853151054606),
}

EXPECTED_FEATURE_COLS: List[str] = [
    "weight", "age", "bedroom", "floor", "wall", "fwealthq", "roof",
    "tenurlot", "sex", "electrct", "makesafe", "burn", "tenurhws",
    "segregate", "composting", "drinksafe", "dump", "collect",
    "toilet_1.0", "wdrinkng_41.0", "wdrinkng_14.0", "fuelmain_6.0",
    "wdrinkng_91.0", "ethnicity", "wdrinkng_11.0", "toilet_2.0",
    "fuelmain_2.0", "fuelmain_5.0", "wdrinkng_12.0", "regcode_8", "regcode_10",
]

GUARD_TOLERANCE = 1e-12

#: XGBoost version recorded inside model_Exp4_ADASYN_XGB.json ("version": [3, 4, 1]).
#: A booster saved by one major version and loaded by another can load without
#: raising and score differently, so requirements.txt pins this exact version.
EXPECTED_XGBOOST_VERSION = "3.4.1"

# --------------------------------------------------------------------------
# Encoding scheme (notebook cell 17)
#
# The suffix format is NOT uniform and must not be generated by a single rule.
# `regcode` was an integer column in train.csv, so pandas.get_dummies produced
# `regcode_8`; `toilet`, `wdrinkng` and `fuelmain` were float columns, so it
# produced `toilet_1.0` and so on. Each pair is written out explicitly and
# checked against feature_cols at load time.
# --------------------------------------------------------------------------

ONE_HOT_SCHEME: Dict[str, List[Tuple[float, str]]] = {
    "toilet": [(1.0, "toilet_1.0"), (2.0, "toilet_2.0")],
    "wdrinkng": [
        (11.0, "wdrinkng_11.0"),
        (12.0, "wdrinkng_12.0"),
        (14.0, "wdrinkng_14.0"),
        (41.0, "wdrinkng_41.0"),
        (91.0, "wdrinkng_91.0"),
    ],
    "fuelmain": [(2.0, "fuelmain_2.0"), (5.0, "fuelmain_5.0"), (6.0, "fuelmain_6.0")],
    "regcode": [(8.0, "regcode_8"), (10.0, "regcode_10")],
}

#: Flat set of every generated one-hot column name.
ONE_HOT_NAMES = {name for pairs in ONE_HOT_SCHEME.values() for _, name in pairs}

#: Columns passed to the model untouched, as raw integer codes.
PASS_THROUGH_COLS: List[str] = [
    "bedroom", "floor", "wall", "fwealthq", "roof", "tenurlot", "sex",
    "electrct", "makesafe", "burn", "tenurhws", "segregate", "composting",
    "drinksafe", "dump", "collect", "ethnicity",
]

#: Columns the booster declares as integer-typed. Source: the exported model
#: file's ``learner.feature_types``, which marks `sex` and `ethnicity` as "int",
#: the twelve one-hot columns as "i" (indicator) and everything else as "float".
#: XGBoost validates the schema of a named DataFrame at predict time, so the
#: dtypes are aligned here rather than left to whatever pandas inferred.
INT_COLS: List[str] = ["sex", "ethnicity"]

#: Columns standardised at inference. Height is absent by design: Section 1.6
#: Limitation 1 excludes it from the feature set to prevent target leakage, so
#: the tool neither requests nor accepts it.
SCALED_COLS: List[str] = ["weight", "age"]

#: Every raw column a caller must supply.
REQUIRED_RAW_COLS: List[str] = SCALED_COLS + PASS_THROUGH_COLS + list(ONE_HOT_SCHEME)

# --------------------------------------------------------------------------
# Tier definitions (Table 3.7, quoted verbatim from the paper) and the tier
# performance actually observed on the test partition (Table 4.10, Section 4.7.2).
# --------------------------------------------------------------------------

HIGH, MONITOR, ONTRACK = "High Priority", "Needs Monitoring", "On Track"
TIER_ORDER: List[str] = [HIGH, MONITOR, ONTRACK]

ACTION_PROTOCOL: Dict[str, str] = {
    HIGH: (
        "Immediate nutritional assessment and intervention by a licensed "
        "health professional at the Rural Health Unit."
    ),
    MONITOR: (
        "Scheduled regular growth monitoring (monthly) by Barangay Health "
        "Workers; supplementary feeding programme inclusion if applicable."
    ),
    ONTRACK: (
        "Routine surveillance at standard intervals; general health and "
        "nutrition promotion for parents."
    ),
}

#: Section 4.7.2, Table 4.10. Held-out test partition, n = 8,632.
TIER_PRECISION_PCT: Dict[str, float] = {HIGH: 27.78, MONITOR: 4.79, ONTRACK: 0.83}
TIER_REFERENCE_COUNTS: Dict[str, int] = {HIGH: 1724, MONITOR: 877, ONTRACK: 6031}
BASE_RATE_PCT = 6.61
TEST_PARTITION_N = 8632

DISCLAIMER = (
    "Screening result only. This is not a diagnosis and does not replace "
    "in-person assessment by a health professional. On the held-out test "
    f"partition, {TIER_PRECISION_PCT[HIGH]:.2f} per cent of the children placed in "
    "the High Priority tier were in fact severely stunted, against a base rate of "
    f"{BASE_RATE_PCT:.2f} per cent. A High Priority result is therefore a trigger "
    "for assessment, not a finding of severe stunting."
)


class ToolError(RuntimeError):
    """Raised when the tool cannot score safely. Never caught to fall back."""


# --------------------------------------------------------------------------
# Loading and guarding
# --------------------------------------------------------------------------


def load_manifest(path: Path = MANIFEST_PATH) -> Dict[str, Any]:
    """Read the exported manifest, raising an actionable error if absent."""
    if not path.exists():
        raise ToolError(
            f"{path} not found. Copy model_Exp4_ADASYN_XGB.json and manifest.json "
            "from Drive (dataset/model_outputs/tool_bundle/) into the artefacts/ folder."
        )
    with open(path, "r", encoding="utf-8") as fh:
        return json.load(fh)


def check_manifest(manifest: Dict[str, Any]) -> List[str]:
    """Compare the manifest against the hard-coded expectations.

    Returns a list of human-readable discrepancies; an empty list means the
    manifest matches and scoring may proceed (Section 3.13.2).
    """
    problems: List[str] = []

    if manifest.get("model_name") != EXPECTED_MODEL_NAME:
        problems.append(
            f"model_name: manifest has {manifest.get('model_name')!r}, "
            f"expected {EXPECTED_MODEL_NAME!r}"
        )
    if manifest.get("severe_class_index") != EXPECTED_SEVERE_INDEX:
        problems.append(
            f"severe_class_index: manifest has {manifest.get('severe_class_index')!r}, "
            f"expected {EXPECTED_SEVERE_INDEX}"
        )
    if list(manifest.get("feature_cols", [])) != EXPECTED_FEATURE_COLS:
        problems.append(
            "feature_cols: the manifest's feature list differs from the one this "
            "application was written against (order and membership must match exactly)"
        )
    for key, expected in (("tau_H", EXPECTED_TAU_H), ("tau_M", EXPECTED_TAU_M)):
        got = manifest.get(key)
        if got is None or abs(float(got) - expected) > GUARD_TOLERANCE:
            problems.append(f"{key}: manifest has {got!r}, expected {expected!r}")

    for col, expected_val in EXPECTED_IMPUTE.items():
        got = manifest.get("impute", {}).get(col)
        if got is None or abs(float(got) - expected_val) > GUARD_TOLERANCE:
            problems.append(f"impute[{col}]: manifest has {got!r}, expected {expected_val!r}")

    for col, (mu, sd) in EXPECTED_SCALER.items():
        got = manifest.get("scaler", {}).get(col)
        if (
            not isinstance(got, Sequence)
            or len(got) != 2
            or abs(float(got[0]) - mu) > GUARD_TOLERANCE
            or abs(float(got[1]) - sd) > GUARD_TOLERANCE
        ):
            problems.append(f"scaler[{col}]: manifest has {got!r}, expected [{mu!r}, {sd!r}]")

    # The encoding scheme must account for every one-hot column and no others.
    generated = {name for pairs in ONE_HOT_SCHEME.values() for _, name in pairs}
    accounted = set(SCALED_COLS) | set(PASS_THROUGH_COLS) | generated
    unexplained = [c for c in EXPECTED_FEATURE_COLS if c not in accounted]
    if unexplained:
        problems.append(f"feature columns this encoder cannot produce: {unexplained}")

    return problems


def check_model_schema(manifest: Dict[str, Any]) -> List[str]:
    """Verify the exported booster against the manifest, without loading xgboost.

    The model file is plain JSON, so its recorded feature names, feature types,
    class count and library version can be read directly. A mismatch here means
    the bundle is internally inconsistent and must be re-exported (EP-5).
    """
    problems: List[str] = []
    model_path = ARTEFACTS / manifest["model_file"]
    if not model_path.exists():
        return [f"{model_path} not found; copy the bundle from Drive into artefacts/"]

    with open(model_path, "r", encoding="utf-8") as fh:
        blob = json.load(fh)
    learner = blob.get("learner", {})

    version = ".".join(str(v) for v in blob.get("version", []))
    if version != EXPECTED_XGBOOST_VERSION:
        problems.append(
            f"model file was saved by xgboost {version}, expected "
            f"{EXPECTED_XGBOOST_VERSION}; update the pin in requirements.txt"
        )
    if list(learner.get("feature_names", [])) != list(manifest["feature_cols"]):
        problems.append("booster feature_names differ from manifest feature_cols")
    n_class = learner.get("learner_model_param", {}).get("num_class")
    if str(n_class) != "3":
        problems.append(f"booster num_class is {n_class!r}, expected 3")

    declared = dict(zip(learner.get("feature_names", []), learner.get("feature_types", [])))
    for col, kind in declared.items():
        if kind == "i" and col not in ONE_HOT_NAMES:
            problems.append(f"booster marks {col!r} as an indicator; the encoder does not")
        if kind == "int" and col not in INT_COLS:
            problems.append(f"booster marks {col!r} as int; INT_COLS does not list it")
    return problems


def load_model(manifest: Dict[str, Any]):
    """Load the fitted booster from XGBoost's native JSON format.

    xgboost is imported here rather than at module scope so that the
    preprocessing path can be exercised in environments where it is absent.
    """
    try:
        from xgboost import XGBClassifier
    except ImportError as exc:  # pragma: no cover
        raise ToolError(
            "xgboost is not installed in this environment. Activate the virtual "
            "environment and run: pip install -r requirements.txt"
        ) from exc

    model_path = ARTEFACTS / manifest["model_file"]
    if not model_path.exists():
        raise ToolError(
            f"{model_path} not found. Copy the model file named in manifest.json "
            "from Drive into the artefacts/ folder."
        )
    model = XGBClassifier()
    model.load_model(str(model_path))
    return model


def load_codebook(path: Path = CODEBOOK_PATH) -> pd.DataFrame:
    """Load the ENNS codebook used to label the form's dropdown options."""
    if not path.exists():
        raise ToolError(
            f"{path} not found. Copy claude_ENNS_codebook_FILLED.csv into "
            "artefacts/ and rename it enns_codebook.csv."
        )
    cb = pd.read_csv(path)
    cb["code"] = pd.to_numeric(cb["code"], errors="coerce")
    return cb


def options_for(codebook: pd.DataFrame, variable: str) -> List[Tuple[float, str]]:
    """Return ``(code, label)`` pairs for one variable, ordered by code."""
    rows = codebook[codebook["variable"] == variable].sort_values("code")
    label_col = "label_TO_FILL" if "label_TO_FILL" in rows.columns else rows.columns[-1]
    return [(float(r.code), str(getattr(r, label_col))) for r in rows.itertuples()]


# --------------------------------------------------------------------------
# Preprocessing
# --------------------------------------------------------------------------


def load_thresholds_json(path: Path = THRESHOLDS_PATH) -> Dict[str, Any]:
    """Load the Section 3.11 operating-point statistics, if present.

    These are the exact figures reported in Sections 4.7.1 and 5.2.3. They are
    displayed in preference to any value interpolated from the trade-off grid,
    which is sampled at 0.001 and therefore does not land on tau_H exactly.
    """
    if not path.exists():
        return {}
    with open(path, "r", encoding="utf-8") as fh:
        return json.load(fh)


def load_surface(path: Path = SURFACE_PATH) -> pd.DataFrame:
    """Load the sensitivity/specificity trade-off surface, if present."""
    if not path.exists():
        return pd.DataFrame()
    return pd.read_csv(path)


def surface_at(surface: pd.DataFrame, threshold: float) -> Dict[str, float]:
    """Nearest grid point on the trade-off surface.

    The grid is sampled every 0.001, so the returned row is an approximation
    for any threshold that does not fall on a grid point. Callers must label it
    as such rather than reporting it as the value at the threshold itself.
    """
    if surface.empty:
        return {}
    row = surface.iloc[(surface["threshold"] - float(threshold)).abs().idxmin()]
    return {k: float(row[k]) for k in surface.columns}


def preprocess(raw: pd.DataFrame, manifest: Dict[str, Any]) -> pd.DataFrame:
    """Turn raw ENNS-coded records into the 31-column model input matrix.

    The order of operations reproduces the notebook: impute with the training
    partition's median (continuous) or mode (categorical), standardise weight
    and age with the training partition's mean and standard deviation, one-hot
    encode the four nominal fields, then reindex to ``feature_cols``.

    A missing raw column raises rather than being filled with zeros, because a
    silently zero-filled column scores without error and scores wrongly.
    """
    missing = [c for c in REQUIRED_RAW_COLS if c not in raw.columns]
    if missing:
        raise ToolError(f"input is missing required columns: {missing}")

    df = pd.DataFrame(index=raw.index)

    # 1. Numeric coercion and imputation (notebook cell 14).
    for col in REQUIRED_RAW_COLS:
        series = pd.to_numeric(raw[col], errors="coerce")
        if col in manifest["impute"]:
            series = series.fillna(float(manifest["impute"][col]))
        df[col] = series

    # `sex` and `ethnicity` carry no imputation value because neither had a
    # missing value in either partition. A missing one here is a data-entry
    # error and must stop the run rather than be guessed at.
    for col in ("sex", "ethnicity"):
        if df[col].isna().any():
            raise ToolError(
                f"{col} is missing for {int(df[col].isna().sum())} record(s); "
                "it has no imputation value in the manifest and must be supplied."
            )

    # 2. Standardisation -- weight and age only (notebook cell 14).
    for col in SCALED_COLS:
        mean, std = manifest["scaler"][col]
        df[col] = (df[col] - float(mean)) / float(std)

    # 3. One-hot encoding (notebook cell 17).
    for source, pairs in ONE_HOT_SCHEME.items():
        for level, name in pairs:
            df[name] = df[source] == level

    # 4. Column order and dtypes, exactly as the booster was trained.
    matrix = df[list(manifest["feature_cols"])].copy()
    for col in matrix.columns:
        if col in ONE_HOT_NAMES:
            matrix[col] = matrix[col].astype(bool)
        elif col in INT_COLS:
            matrix[col] = matrix[col].astype("int64")
        else:
            matrix[col] = matrix[col].astype("float64")

    if matrix.isna().any().any():
        bad = matrix.columns[matrix.isna().any()].tolist()
        raise ToolError(f"unresolved missing values remain in: {bad}")
    return matrix


# --------------------------------------------------------------------------
# Scoring and tiering
# --------------------------------------------------------------------------


def predict_severe_proba(model, matrix: pd.DataFrame, manifest: Dict[str, Any]) -> np.ndarray:
    """Return P(Severely Stunted) -- column 2 of the class-probability array."""
    return model.predict_proba(matrix)[:, int(manifest["severe_class_index"])]


def assign_tier(p: float, tau_h: float, tau_m: float) -> str:
    """Equations 3.15 to 3.17 (Section 3.11.2)."""
    if p >= tau_h:
        return HIGH
    if p >= tau_m:
        return MONITOR
    return ONTRACK


def assign_tiers(probs: Sequence[float], tau_h: float, tau_m: float) -> pd.Series:
    """Vectorised form of :func:`assign_tier`."""
    arr = np.asarray(probs, dtype=float)
    return pd.Series(
        np.where(arr >= tau_h, HIGH, np.where(arr >= tau_m, MONITOR, ONTRACK)),
        index=getattr(probs, "index", None),
    )


def blank_template() -> pd.DataFrame:
    """One empty row carrying the exact headers batch mode expects."""
    return pd.DataFrame([{col: "" for col in ["child_id"] + REQUIRED_RAW_COLS}])
